apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: cs3219
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Use NodePort for testing; change to ClusterIP if not exposing externally
